[package]
name = "cosinewaves/lambda"
description = "A lightweight lifecycle orchestrator"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
Promise = "lukadev-0/typed-promise@4.0.2"