[package]
name = "cosinewaves/lambda"
description = "a lightweight, lifecycle-aware module loader for roblox"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"

[dependencies]
